name: "OpenVPN Client"
version: "0.7.1"
slug: "openvpn_client"
description: "An OpenVPN Client for your Home Assistant"
init: false
arch:
  - aarch64
  - amd64
startup: services
ingress: true
apparmor: true
map:
  - addon_config:rw
host_network: true
privileged:
  - NET_ADMIN
