name: "OpenVPN Client"
version: "0.6.2"
slug: "openvpn_client"
description: "An OpenVPN Client for your Home Assistant"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: true
map:
  - addon_config:rw
host_network: true
privileged:
  - NET_ADMIN
